### ISSUE TITLE
两个默认值是True的就算取消勾也没效果

### ISSUE THREAD

**Issue by eachgo** [RikaCelery/N_m3u8DL-RE_Command_Generator#2]
--auto-subtitle-fix 
和
--use-system-proxy

这两个选项选不选都没区别

感觉需要改成不勾选的时候

输出 --auto-subtitle-fix  "False"

**Comment by RikaCelery** [comment]
好的，我回去看看

**Comment by RikaCelery** [comment]
在 [fix-default-value](https://github.com/RikaCelery/N_m3u8DL-RE_Command_Generator/tree/fix-default-value) 这个分支修了
