### ISSUE TITLE
老大你这个怎么下载

### ISSUE THREAD

**Issue by whxuezhe** [RikaCelery/N_m3u8DL-RE_Command_Generator#7]
Beta版吗？似乎也没提供下载途径啊！？我是一介小白，有github的朋友推荐我这个，因此我刚接触N_m3u8DL-RE；官方的命令参数语法、我个人理解学习能力不行，不懂咋用-

**Comment by RikaCelery** [comment]
https://github.com/RikaCelery/N_m3u8DL-RE_Command_Generator/blob/main/generator.html

下载即可

**Comment by nilaoda** [comment]
开个 GitHub Pages 托管一下更方便

**Comment by RikaCelery** [comment]
@nilaoda 确实，一会儿开一下

**Comment by RikaCelery** [comment]
Pages 链接已更新到README #15
